language: ruby
cache: bundler
sudo: false
rvm:
  - 2.2.0

env:
  - DB=mysql

services:
  - couchdb
  - redis-server

before_script:
  - memcached -p 11211 &
  - cp .env.travis .env
  - mkdir -p tmp/pids tmp/files tmp/reports
  - cd frontend && npm install
  - cd ../ && npm install -g istanbul codeclimate-test-reporter
  - bundle exec rake db:setup RAILS_ENV=test

script:
  - bundle exec rspec
  - bundle exec teaspoon
  - CODECLIMATE_REPO_TOKEN=c2515476ac88e8540c23b121b6dadb75188482db1d5c39516208b2ea7485a907 codeclimate < ./coverage/default/lcov.info

after_failure:
  - cat /home/travis/build/articlemetrics/lagotto/tmp/capybara/*.html

env:
  global:
    secure: I7KspoNlLUt6d/EuxHixFzeEmmyS7C8oABXvSshwivrolPeylGJn3yRyzkTsk86pCBeAssDD/ozAVde2XrPDDpmcXZPvBZz7S1YZj4Wt7MHdOlHMT8zujx/+HQaz07Yy7efjoTF7MJNegn0nbh9+pNhx/o/GF+FIDEGX3bLEY58=

addons:
  code_climate:
    repo_token: c2515476ac88e8540c23b121b6dadb75188482db1d5c39516208b2ea7485a907

notifications:
  hipchat:
    matrix:
    - aff7ea27f6120805aee5aacc2dc36b@alm
    rooms:
      secure: Cl8g3DaeJgO17tl+1dHGQIn/Ra2h3bYWhZsZcWVxsCAUFeD8HgXlqpAYVCvTUai1nUyy5BO5k6AJL8frwoYnT2IZUkh3w7/WcuIpGEXmCwTOJyDs+82QhK3chP8COqPzEEy3x1wyF8KC7zYvLjH3wQi4mhhFxFjp4vPu2+Xj4aY=
    template:
      - '%{repository}#%{build_number} (%{branch} - %{commit} : %{author}): %{message} (<a href="%{build_url}">Details</a>/<a href="%{compare_url}">Change view</a>)'
    format: html
  slack: lagotto:PQRg85DOsMv4EJCi1CUNi2AE
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/a275593b238b22c47314
    on_success: change
    on_failure: always
    on_start: false
