language: ruby
rvm:
  - 1.9.3
env:
  - DB=mysql
script:
  - RAILS_ENV=test bundle exec rake db:migrate --trace
  - bundle exec rake db:test:prepare
  - bundle exec rake
before_script:
  - cp config/settings.yml.example config/settings.yml
  - cp config/database.yml.example config/database.yml
  - mysql -e 'create database alm_test'