defaults: &defaults
  pool: 5
  timeout: 5000
  database: lagotto_<%= Rails.env %>
  adapter: mysql2
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  host: <%= ENV['DB_HOST'] %>

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
